FROM alpine:3.20 AS builder

USER root

RUN apk add --no-cache \
    git alpine-sdk \
    xz bc \
    flex \
    bash \
    curl wget sudo \
    man-db man-pages file shadow \
    gawk diffutils findutils
