FROM debian:12-slim AS builder

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
ENV DEBIAN_SYS=1

RUN apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y sed; \
    apt-get update; \
    apt-get install -y \
        curl wget sudo git \
        xz-utils bc file \
        bash; \
    apt-get clean
